[package]
name = "builtins-wasm"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
dtoa = {version = "1.0.11", features = ["no-panic"] }
fast-float2 = { path = "../../fast-float-rust", default-features = false, features = ["no-panic"] }
itoa = { version = "1.0.15", features = ["no-panic"] }
lexical-core = { version = "1.0.6", default-features = false, features = ["parse-integers"] }
no-panic = "0.1"
wasi = "0.11"

[profile.release]
lto = true
codegen-units = 1

[workspace]
